/** Review-brief contract declared by guide steps; absent keeps the chapter guide. */
export const BRIEF_CONTRACT = "brief-v1";
/** Appended at runtime even to frozen/custom guide definitions. */
export const guideArtifactInstructions = `For large results, save the COMPLETE guide JSON under /resultSubmission/directory, call submit_result_artifact with a relative path, and return the bounded factoryArtifact envelope as your entire final response. Runtime applies the identical schema/coverage/revision/evidence checks to inline and artifact results. The complete file inventory is runtime-owned at /progress/reviewScope/files. To avoid duplicating path strings, scope.files may be "runtime", and each chapter may use fileIndexes:[zero-based indexes into that inventory] instead of files. Map every changed file to a feature-oriented chapter; missing, duplicate or unknown indexes still block publication. Never mix files and fileIndexes in one chapter. The saved/published guide retains all exact file paths and normal review-file bindings.`;
export const guideMapInstructions = `Every newly authored guide requires scope:{kind:"purely-visual"|"nonvisual",rationale,files:[every exact /progress/reviewScope/files path once]}. Classify the COMPLETE PR against its accepted requirements and actual diff. Explain why every file is purely visual to use that exemption; screenshots alone never establish it. Technical, logic, structural, supporting nonvisual and mixed changes use nonvisual. Nonvisual guides MUST contain a meaningful system:{lanes:[{id,name}],parts:[{id,label,laneId,status:"new"|"changed"|"unchanged"|"legacy"}],before:[{source,target,label?,weak?}],after:[{source,target,label?,weak?}]} with 3–6 meaningful lanes and stable unique part IDs. Connections are directed, truthful and may be empty. Every changed chapter and every logic/structural chapter requires nonempty systemPartIds referencing the parts it touches. Link supporting material where relevant; do not invent parts or relationships. Missing maps/links require bounded guide-only output correction, retaining implementation, reviews, captures and snapshots. Older saved guides remain readable without rewriting their artifacts.`;

/**
 * Stock review-brief prompt. The reader decides one thing: does this PR deliver
 * what was asked? Content is ordered to answer that, with honest, checkable proof.
 */
export const briefPrompt = `Write the human review brief for the WHOLE PR at the current revision, including inherited takeover work and every accepted iteration. The reader decides one thing: does this PR deliver what was asked? Answer in this order: was the right thing built (the ask and every interpretation of it), does it work (one decisive, human-checkable proof per requirement), what only a human can judge, and what else changed or remains unproven.
First read through factory-context: the original input/ticket and all comments, clarification decisions and answers, the frozen requirement inventory and review-gate coverage, the accepted plan, /progress/reviewScope (every whole-PR file), executed QA stories with observed values, and the accepted capture inventory. Inspect the actual base-to-head diff yourself.
Return {"verdict":{"headline":"what now works, said the way a user would say it (<=160 chars)","readiness":"ready|ready-with-caveats|not-ready","why":"one sentence (<=260)"},"ask":{"source":"e.g. Linear ATT-764","url":"ticket URL when known","quote":"the original request verbatim, trimmed to its substance"},"interpretation":[{"topic":"short","chosen":"what was built","alternatives":["what the ask could also have meant"],"decidedBy":"you|ticket|bob","note":"optional, e.g. You delegated this choice."}],"requirements":[{"id":"kebab-id","text":"observable outcome (<=180)","origin":"ask|your-answer|bob","covers":["frozen inventory requirement IDs"],"status":"shown|tested|partly|not-shown|gap|waived","proof":PROOF,"more":[PROOF],"caveat":"optional limit specific to this line","files":["exact changed files that implement it"]}],"yourCall":[{"question":"...?","context":"the facts a person needs","bobChose":"what was built and why","proof":PROOF}],"beyondAsk":[{"what":"...","why":"...","attention":"none|low|look","files":["..."]}],"notVerified":[{"what":"...","why":"..."}],"noticed":["pre-existing problem seen but not changed"],"hygiene":[{"text":"satisfied process criterion, e.g. No generated code committed","covers":["inventory IDs"]}]}. Add "system" only as described below.
PROOF is exactly one of:
{"kind":"screens","shots":[{"area":"exact capture area","state":"exact capture state","label":"what to look at","focus":{"x":0,"y":0,"w":100,"h":100}}],"note":"optional"}: focus crops the image, in percent, to the pixels that prove the claim (open the image to choose it). Prefer pairs varying only the condition under test (English vs German, setting A vs B, before vs after).
{"kind":"video","taskId":"...","sha256":"...","label":"..."}: from the accepted video inventory.
{"kind":"table","method":"how it was observed","columns":["Given","Observed"],"rows":[{"cells":["...","..."],"mark":"good|bad|neutral"}]}: quote actual observed values (rendered text, HTTP status, payload fields) from QA receipts. Use it as a decision table for business rules, marking where a rule does nothing as bad.
{"kind":"code","file":"repository-relative path","excerpt":"at most 25 lines of the real diff, +/- prefixed","note":"why this proves it"}
{"kind":"test","file":"...","excerpt":"test names or the key assertion","result":"what passed"}
{"kind":"command","command":"...","output":"trimmed real output","note":"optional"}
{"kind":"steps","steps":[{"label":"...","detail":"...","change":"new|changed|manual"}]}: only when the requirement IS a linear sequence.
{"kind":"flowRef","flow":"flow-id","steps":[1,2],"note":"..."}: points at steps of a system flow.
Rules:
- Status describes the proof honestly: shown = a human-visible observation at this revision proves it; tested = only automated tests prove it; partly = some cases proven and the caveat names what is not; not-shown = no evidence; gap = not met; waived = deliberately skipped by an accepted decision. A passed label, an implementation receipt or source reading alone is not proof.
- Every proof is judgeable in about 30 seconds without opening a file. Observed values beat descriptions. Never invent values; take them from executed receipts.
- Screenshots appear only as proof of one claim or one decision, each with a label and a focus crop. No galleries, no decorative images, no repeats.
- interpretation lists every place the ask had to become a concrete decision: added or narrowed scope, UX choices, defaults, migration behavior. decidedBy is bob whenever no human answer or ticket text made the call, including delegated choices; these are where results quietly diverge from requests.
- yourCall holds only what a person must judge: taste, trade-offs, consequences for users, security or compatibility decisions, wording. Ask each as a question and say what Bob chose. Use 0-4 items; an empty list is right for mechanical changes. Never ask the reviewer to redo QA.
- Group the inventory into 1-12 lines a person would check separately. Every active inventory requirement appears in requirements[].covers, or in hygiene[].covers for process criteria (generated files, branch continuity, changelog policy, tracker state). Every file in /progress/reviewScope/files appears in a requirement line or a beyondAsk item.
- beyondAsk lists behavior and code no requirement asked for: refactors, shared code affecting other features, dependency, configuration and migration changes, behavior changes for existing users. Read the diff for changed defaults, removed fallbacks, widened permissions and new public endpoints. Use attention look when it can affect users or other code paths.
- notVerified states up to 4 product-relevant evidence limits (real services replaced by fixtures, untested environments or devices). noticed lists pre-existing problems you saw but did not change.
- Pipeline process (CI retries, PR selection, tracker synchronization, earlier rounds, reviewer tooling) is not review content; put anything a person must know into one hygiene line. The runtime shows PR, revision, CI and diff statistics.
- No local absolute paths, commit SHAs, QA story or criterion IDs, receipt filenames or exit codes in prose. Repository-relative paths belong in files and proof file fields only.
- Length follows the change: a few-file fix fits on one screen. Do not pad.
- readiness is not-ready when any line is a gap or required QA failed or is blocked; ready-with-caveats when a yourCall item or a partly line needs attention; otherwise ready.
Add "system":{"summary":"2-3 sentences","flows":[FLOW],"interfaces":[{"title":"Endpoints|Stored data|Dependencies and configuration","why":"why it matters for the decision","columns":["..."],"rows":[{"cells":["..."],"mark":"new|changed|removed|risk|same"}]}]} ONLY when the change alters how components interact, what data is stored, or where the trust boundary sits. FLOW is {"id":"kebab-id","title":"...","trigger":"what starts it","implements":["requirement ids"],"participants":[{"id":"kebab-id","label":"real component","detail":"class or module","external":true}],"steps":[{"from":"participant id","to":"participant id","label":"real endpoint, event, query or call","detail":"...","change":"new|changed","dashed":true,"outcome":"good|bad"}],"before":[steps for the same trigger before this PR, only when an existing flow changed],"note":"..."}. Flows are sequence diagrams: one per real trigger, 2-6 participants, at most 12 steps, real names; dashed marks steps outside the product's control. Interfaces are fact tables: endpoints (caller, authorization, effect), stored data (fields, lifetime, exposure), dependencies and configuration. Mark rows that move the trust boundary or change behavior for existing users as risk. Never draw box-and-arrow maps.
After a human review, add "sinceLastReview":{"previousHeadSha":"the reviewed revision","summary":"...","changes":[{"what":"what changed in response","files":["..."]}]} and keep the whole brief current. Do not modify product code, recapture screenshots, rerun implementation or merge.`;

/** Appended at runtime to every review-brief step, including frozen and custom ones. */
export const briefRuntimeInstructions = `For large results save the COMPLETE brief JSON under /resultSubmission/directory, call submit_result_artifact with a relative path, and return the bounded factoryArtifact envelope as your entire final response. The runtime stamps the contract, binds the exact whole-PR file snapshot and attaches review coverage; never author contract, reviewFiles or requirementCoverage. To avoid repeating long paths, requirement lines, beyondAsk items and sinceLastReview changes may use fileIndexes:[zero-based indexes into /progress/reviewScope/files] instead of files, never both on one item. The brief describes the COMPLETE cumulative PR, never only the latest repair. On repeats keep unchanged lines and update affected proof. Files come only from /progress/reviewScope/files; base-only integration changes since a previous approval (/progress/approvalDelta) belong in sinceLastReview.summary, not in files. Validation rejects unknown or uncovered inventory IDs, unexplained files, statuses contradicting review coverage, screenshots outside the accepted capture inventory, stale or unaccepted videos, broken flow references, and local paths or SHAs in prose. A rejection returns to you for brief-only correction; implementation, reviews, captures and snapshots are retained.`;

export const briefVideoInstructions = `\nFor video-v1 a requirement may use a video proof {"kind":"video","taskId","sha256","label"} from the current accepted video inventory, when motion or sequence is the point. Watching a clip never approves anything; keep explicit current-revision approval.`;
